spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 10s
      routes:
        - id: keycloak-admin-client-user
          uri: lb://KEYCLOAK-ADMIN-CLIENT
          predicates:
            - Path=/api/v1/user/**
        - id: keycloak-admin-client-group
          uri: lb://KEYCLOAK-ADMIN-CLIENT
          predicates:
            - Path=/api/v1/group/**
        - id: keycloak-admin-client-docs
          uri: lb://KEYCLOAK-ADMIN-CLIENT
          predicates:
            - Path=/keycloak-admin-client/v3/api-docs
        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/v1/task/**
            - Path=/task-service/v3/api-docs

springdoc:
  swagger-ui:
    oauth:
      client-id: Mini-Project
      client-secret: HC3neQnSa1iDHx37zR66kPxPLdKpGHiY
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /keycloak-admin-client/v3/api-docs
        name: Keycloak Admin Client Service
      - url: /task-service/v3/api-docs
        name: Task Service
