spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 10s
      routes:
        - id: keycloak-admin-client
          uri: lb://KEYCLOAK-ADMIN-CLIENT
          predicates:
            - Path= /api/v1/user/**, /api/v1/group/**
        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path= /api/v1/task/**
        - id: keycloak-admin-client-swagger-docs
          uri: lb://KEYCLOAK-ADMIN-CLIENT
          predicates:
            - Path= /v3/api-docs/keycloak-admin-client
          filters:
            - RewritePath= /v3/api-docs/keycloak-admin-client, /v3/api-docs
         - id: task-service-swagger-docs
          uri: lb://TASK-SERVICE
          predicates:
            - Path= /v3/api-docs/keycloak-admin-client
          filters:
            - RewritePath= /v3/api-docs/task-service, /v3/api-docs
springdoc:
  swagger-ui:
    oauth:
      client-id: Mini-Project
      client-secret: 6QgQczQlPf6BB15dtNYPIyQVP6lqjpne
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /keycloak-admin-client/v3/api-docs
        name: Keycloak Admin Client Service
      - url: /task-service/v3/api-docs
        name: Task Service
