# keycloak-admin-client.yml

server:
  port: 9091
  error:
    include-stacktrace: never

spring:
  application:
    name: keycloak-admin-client
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/Mini-Project

keycloak:
  auth-server-url: http://localhost:8080
  realm: Mini-Project
  clientId: Mini-Project
  clientSecret: ZUBxXkJYEMkNWZDhBf6dEyua90e1QdpK

openapi:
  service:
    title: Keycloak Admin Client Doc
    version: 1.0.0
    url: http://localhost:9090

springdoc:
  api-docs:
    path: /keycloak-admin-client/v3/api-docs
  swagger-ui:
    path: /keycloak-admin-client/swagger-ui.html
    oauth:
      client-id: Mini-Project
      client-secret: ZUBxXkJYEMkNWZDhBf6dEyua90e1QdpK

management:
  tracing:
    sampling:
      probability: 1

logging:
  level:
    root: DEBUG
