server:
  port: 9092
  error:
    include-stacktrace: never
  
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://task_postgres:5432/mini_project_db
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

openapi:
  service:
    title: Keycloak Admin Client Doc
    version: 1.0.0
    url: http://localhost:9090

springdoc:
  api-docs:
    path: /task-service/v3/api-docs
  swagger-ui:
    path: /task-service/swagger-ui.html

springdoc:
  swagger-ui:
    oauth:
      client-id: Mini-Project
      client-secret: OC5Slit72vxCYbH7GmZaSA11XQLNUj6z
      
management:
  tracing:
    sampling:
      probability: 1.0
